# Generated by Django 4.2.6 on 2023-10-19 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0005_rename_is_cashier_user_is_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_employee',
            new_name='is_cashier',
        ),
    ]
